### ISSUE TITLE
[BUG] dark mode dropdown issues

### ISSUE THREAD

**Issue by lanbau** [csandman/chakra-react-select#134]
### Description

added this package and was expecting dark mode to work out of the box. But as you can see the options are not visible. Any idea how i can style the options background manually? Can't seem to select it using inspect element

<img width="588" alt="Screenshot 2022-05-23 at 11 18 52 PM" src="https://user-images.githubusercontent.com/5410693/169852336-4a543c18-3a19-4139-aa2a-0f06f1fca2c7.png">

### chakra-react-select Version

4.0.0

### TypeScript?

- [ ] Yes I use TypeScript

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS/iPadOS
- [ ] Android

**Comment by csandman** [comment]
I tested this out and I'm not seeing anything causing this.  See here for a working example: https://codesandbox.io/s/chakra-react-select-demo-65ohb?file=/package.json

I'd need a reproduction to figure out what's causing this.

**Comment by csandman** [comment]
The only thing I would think might be causing this would be that you have modified colors in your chakra theme. If you have any theme customizations, can you post them?

**Comment by aaronleopold** [comment]
I am also facing this issue, happy to share my usage! I'll link the relevant pieces of information, please let me know if there is anything else you might need. 

Here is my [theme config](https://github.com/aaronleopold/stump/blob/develop/packages/core/frontend/src/util/theme.ts)
This is the [component](https://github.com/aaronleopold/stump/blob/develop/packages/core/frontend/src/components/TagSelect.tsx) I am working on (pushed early so I can showcase what's happening). I set `menuIsOpen` so I can inspect it, @lanbau that should help you out debugging since you said you can't select it to inspect it.

### chakra-react-select Version

4.0.0

### TypeScript?

- [x]  Yes I use TypeScript

### Operating System

- [x]  macOS
- [ ]  Windows
- [ ]  Linux
- [ ]  iOS/iPadOS
- [ ]  Android

**Comment by edulanasca** [comment]
Hi, I am also facing this issue, I think it might be the css. I've noticed that in the demo you provided @csandman 

The button has `--chakra-colors-whiteAlpha-300`
![image](https://user-images.githubusercontent.com/43045722/170831270-b51397dd-e9c7-4695-ae04-21b09cce539b.png)

This is what I imported in my project, it uses `--chakra-colors-gray-100`
![image](https://user-images.githubusercontent.com/43045722/170831301-01b07755-04ee-49c3-a05c-3dab38a16f61.png)

This is my theme config file, I just enabled dark mode https://gist.github.com/edulanasca/71679919953fcb4cee88506393ab62f4

Hope this can help

**Comment by aaronleopold** [comment]
Another update, a friend of mine tried on a windows machine on a Firefox browser and it was working:

![image](https://user-images.githubusercontent.com/36278431/170840171-247bbf0d-66e3-45a9-ab19-decd766be173.png)

**Comment by lanbau** [comment]
i overcame it with a hack...

```
import type { ChakraStylesConfig } from "chakra-react-select";

const chakraStyles: ChakraStylesConfig = {
    dropdownIndicator: (provided, state) => ({
      ...provided,
      background: state.isFocused ? "blue.100" : "002C5C",
      p: 0,
      w: "40px",
    }),
    option: (provided, state) => ({
      ...provided,
      background: "#002C5C",
    }),
  };
```

```
<Select<any>
                  {...field}
                  chakraStyles={chakraStyles}
                  isMulti
                  options={options}
                  placeholder="Select countries"
                  closeMenuOnSelect={false}
                />
```

**Comment by csandman** [comment]
I can see that multiple people are having this issue so I believe that there is some common thread that's causing it, but for some reason I still can't seem to make the issue happen.

I think the biggest clue is the comment from @edulanasca about how the styling is using `gray.100` instead of `whiteAlpha.300` on his local version.  This confuses me however, specifically because I'm not setting that value manually.  It is coming directly from the theme styles for the `addon` component from the `Input`'s multi-part component theme.

The same goes for the dropdown part, which is using the theme styles from `list` component from the `Menu`'s theme. So if it's happening for this, I'd think it would also be happening for the normal menu component/input addon component? It would be good to know if anyone could confirm that.

Besides that, it would also be very helpful to know what specific package versions of chakra, emotion, etc. that people are on so I can try and reproduce this more easily.  I'll continue trying to reproduce this in the meantime.

**Comment by aaronleopold** [comment]
> I just tested your develop branch on my machine (M1 MacBook Air, with Chrome) and it appears to be working correctly for me

Super strange! If I come across anything that helps resolve this issue I can update the thread here, otherwise I'm okay keeping the manual styling I've added for now.

Also, thanks!! It's a long ways away until a release, but I'm glad you liked it and that you got it up and running! I was a little worried people would have issues after helping my friend get it running on windows 😅

**Comment by csandman** [comment]
Good to know!  If anyone else is running into this issue after updating everything, try doing a clean install.

**Comment by edulanasca** [comment]
Yup, it's working now, I forgot to mention I'm on Windows, with Chrome. Thanks @csandman

**Comment by csandman** [comment]
@edulanasca glad to hear it!

And @aaronleopold I realized that this might be an issue because I noticed in your `package.json` in your main branch you had these dependency versions:

```json
"@chakra-ui/react": "^1.8.8",
"chakra-react-select": "^4.0.0",
"react": "^18.1.0",
"react-dom": "^18.1.0",
```

So there's a fair chance you ended up with your main dependencies while on your development branch.

**Comment by csandman** [comment]
I'm going to convert this to a discussion so I can highlight the answer
