### ISSUE TITLE
menuPlacement prop isn't working

### ISSUE THREAD

**Issue by onx2** [csandman/chakra-react-select#17]
**Describe the bug**
menuPlacement

**Link to Reproduction**
[A link to a CodeSandbox with a minimal reproduction of the bug you're experiencing.](https://codesandbox.io/s/chakra-react-select-demo-forked-xx56e?file=/example.js)

**Expected behavior**
menuPlacement prop gets passed along to react-select

**Comment by csandman** [comment]
I have a PR that someone is reviewing right now to fix this. The prop was getting passed but the way I implemented my custom menu popover didn't take it into account when positioning. Thanks for the bug report!

**Comment by csandman** [comment]
Ok, a new version has been published!  You can check it out here: https://codesandbox.io/s/chakra-react-select-menuplacement-fix-xizwb?file=/example.js

In your example, I had to move the `menuPlacement="top"` to the third select component in order to demonstrate, because with the way `react-select` handles top placement, there needs to be enough room above the element in order to show it there, otherwise it defaults to the bottom.
