### ISSUE TITLE
[BUG] ValueContainer component attempts to access `px` in possibly undefined styles object

### ISSUE THREAD

**Issue by dheekshitakumar** [csandman/chakra-react-select#198]
### Description

When I test the Select component, I expected the component to render but instead a TypeError occurs:  'TypeError: Cannot read properties of undefined (reading 'px')'

### chakra-react-select Version

4.2.4

### Link to Reproduction

https://codesandbox.io/s/reverent-feynman-midkvj?file=/__tests__/Select.test.js

### TypeScript?

- [ ] Yes I use TypeScript

### Steps to reproduce

1. Go to the [CodeSandbox link](https://codesandbox.io/s/reverent-feynman-midkvj?file=/__tests__/Select.test.js)
2. Run the tests / Click on the 'Tests' tab
3. See error

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS/iPadOS
- [ ] Android

### Additional Information

The issue seems to be coming from the 'ValueContainer' component in[ chakra-components/containers.tsx](https://github.com/csandman/chakra-react-select/blob/main/src/chakra-components/containers.tsx).

A styles object `inputStyles` is created with `useMultiStyleConfig()` in line 77.

```js
const inputStyles = useMultiStyleConfig("Input", {
    size,
    variant,
  });
```

When creating the `initialSx` component - `inputStyles.field.px` is accessed. I believe the issue occurs when `inputStyles.field` is undefined and throws an error.

```js
  const initialSx: CSSObject = {
    display: "flex",
    alignItems: "center",
    flex: 1,
    paddingY: "2px",
    paddingX: inputStyles.field.px, //this is where the issue is - line 87
    flexWrap: "wrap",
    WebkitOverflowScrolling: "touch",
    position: "relative",
    overflow: "hidden",
  };
```

A possible solution to this may be to add optional chaining to check if the field exists before accessing it?

**Comment by csandman** [comment]
This occurs because the `ChakraProvider` is required in order for this component to work.  See this thread for more info: https://github.com/csandman/chakra-react-select/issues/19#issuecomment-993008625

I have looked into making it so some of these styles being accessed from the theme don't cause the component to break but there isn't much point to it as the application looks entirely unstyled.

This is easy enough to fix if you pass the `ChakraProvider` into the `wrapper` option of the `render` function:

```js
import "@testing-library/jest-dom";
import { ChakraProvider } from "@chakra-ui/react";
import { Select } from "chakra-react-select";
import { render, screen } from "@testing-library/react";

describe("When rendering out a <Select /> component", () => {
  it("should render without throwing a TypeError", () => {
    render(<Select size="md" />, { wrapper: ChakraProvider });
    const input = screen.getByRole("combobox");
    expect(input).toBeTruthy();
  });
});
```

CodeSandbox: https://codesandbox.io/s/chakra-react-select-testing-example-56ym6g?file=/__tests__/Select.test.js

**Comment by dheekshitakumar** [comment]
Makes sense! Thanks for the clarification.
