### ISSUE TITLE
[BUG] Cannot select option text

### ISSUE THREAD

**Issue by ffaubert** [csandman/chakra-react-select#222]
### Description

Our end users are complaining that they are unable to copy and paste selected option text. The easiest way to explain this is to view the codesandbox example and try to copy the (pre-selected) text "Blue" using your mouse, or ctrl-a/c. 

Please let me know if I should be chasing this down with the react-select team instead.

### chakra-react-select Version

4.4.1

### Link to Reproduction

https://codesandbox.io/s/copy-and-paste-31evm6?file=/example.js

### TypeScript?

- [ ] Yes I use TypeScript

### Steps to reproduce

1. Go to the code sandbox
2. Observe that "Blue" is already selected in the list
3. Try to copy the word Blue and paste it elsewhere (without right clicking, as that does not work for multiple words)

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS/iPadOS
- [ ] Android

### Additional Information

Thank you for your time!

**Comment by csandman** [comment]
Sorry to say that this behavior is the same in this package as it is in the original `react-select` (see here: https://codesandbox.io/s/lm73rw?module=/example.tsx)

I won't be changing anything in this package that diverges behaviorally from the original package, and this is something that's probably intentional, as it would probably interfere with the typed out value when selecting a new value.

If you'd like this changed, I recommend submitting an issue on the original package.  If they change it there, I would be willing to change it here as well.
