### ISSUE TITLE
Colors not working in demos

### ISSUE THREAD

**Issue by chrisj-back2work** [csandman/chakra-react-select#61]
**Describe the bug**
The "select colors" examples do not display colors correctly.

Example: "Select Colors and Flavours / md" example -- all selections are grey.

Example: "Select Colors and Flavours / with global" -- all selections are purple.

**Link to Reproduction**

The demos you list from this repo's README:

- https://codesandbox.io/s/chakra-react-select-demo-65ohb?file=/example.js

- https://codesandbox.io/s/chakra-react-select-ts-demo-vz9ut?file=/app.tsx

**To Reproduce**

1. Visit either demo sandbox
2. Click a few options in each example

**Expected behavior**
Each selection should use the color of the name selected, as in the README screen shot.

**Screenshots**
![image](https://user-images.githubusercontent.com/68551954/155888263-6321daba-3fac-4604-acb5-9973c5af1eee.png)

**Desktop (please complete the following information):**

- OS: OSX
- Browser: Chrome 98.0.4758.102

**Comment by chrisj-back2work** [comment]
My misunderstanding. Some of the examples aren't meant to use actual colors. Confusing since the choices ARE colors, but I stand corrected.

**Comment by csandman** [comment]
Yeah I can see where the confusion came from, the data I used for these examples came from the original `react-select` examples and colors was just one of the simpler list of options to use for examples.  But yeah, in order to apply a color to the tags you have to use the [`colorScheme`](https://github.com/csandman/chakra-react-select#colorscheme) prop either on the overall `Select` component, or as a key in your options items.
