### ISSUE TITLE
[BUG] Ordering style issue on @emotion/css or @emotion/react when call any component form chakra-react-select

### ISSUE THREAD

**Issue by fransiscushermanto** [csandman/chakra-react-select#66]
**Describe the bug**
This issue happened when call any component from chakra-react-select to your codes.  Normally we can easily overwrite Chakra-UI Provider default Theme but after calling any component from chakra-react-select it changed the ordering and cause emotion become unable to overwrite the styling

**How To Reproduce**
This bugs only happened when you start calling any chakra-react-select component to your codes, if you only install it won't change anything

**Expected behavior**
Expected chakra-ui default style to be low priority

**Screenshots**
[Before]
![image](https://user-images.githubusercontent.com/42550309/157828797-de15ec65-9a79-4a45-848b-b9c09cb81a38.png)

[After]
![image](https://user-images.githubusercontent.com/42550309/157828364-05f659c5-dba7-465c-bb34-5679366db1ee.png)

**Comment by csandman** [comment]
Are you saying the class priorities on the other components in your app are changing when you use this component? How are you applying the styles to your other components, are you using the Chakra style props or CSS?

**Comment by csandman** [comment]
So it's pretty difficult for me to gauge why this is happening with the information provided, especially because I haven't worked with emotion directly very much.  My best guess is that it has something to do with the fact that the core `react-select` has its own dependencies of `@emotion/react` and `@emotion/cache`.  I'm not sure what about this would cause the issue, but that's the only likely reason that the rest of your emotion styles would be affected.

One thing I'd ask is, are the styles which are changing order both from global emotion style sets?  Because according to [a comment from one of emotion's maintainers](https://github.com/emotion-js/emotion/issues/2675#issuecomment-1061619407), the order in which global stylesheets are added is not consistent, and you shouldn't rely on them staying consistent.  And if they're not both from global style sheets, where do the styles in your screenshot above come from specifically?  Which one is from the global stylesheet and which is from a different source?

I might be able to help if you answer those questions, but if not then your best bet is probably to look through [the issues on the react-select repo](https://github.com/JedWatson/react-select/issues?q=is%3Aissue+emotion) to see if someone has a similar issue.  You could also confirm that its a `react-select` issue first by seeing if the same thing happens when you install/import that component instead, but I'm almost positive it is due to the base package and not this wrapper.

**Comment by fransiscushermanto** [comment]
> So it's pretty difficult for me to gauge why this is happening with the information provided, especially because I haven't worked with emotion directly very much. My best guess is that it has something to do with the fact that the core `react-select` has its own dependencies of `@emotion/react` and `@emotion/cache`. I'm not sure what about this would cause the issue, but that's the only likely reason that the rest of your emotion styles would be affected.
> 
> One thing I'd ask is, are the styles which are changing order both from global emotion style sets? Because according to [a comment from one of emotion's maintainers](https://github.com/emotion-js/emotion/issues/2675#issuecomment-1061619407), the order in which global stylesheets are added is not consistent, and you shouldn't rely on them staying consistent. And if they're not both from global style sheets, where do the styles in your screenshot above come from specifically? Which one is from the global stylesheet and which is from a different source?
> 
> I might be able to help if you answer those questions, but if not then your best bet is probably to look through [the issues on the react-select repo](https://github.com/JedWatson/react-select/issues?q=is%3Aissue+emotion) to see if someone has a similar issue. You could also confirm that its a `react-select` issue first by seeing if the same thing happens when you install/import that component instead, but I'm almost positive it is due to the base package and not this wrapper.

Both images from before and after is coming from @emotion/css it's css in js, but I also tried out styling from global emotion it's the ame.

**Comment by fransiscushermanto** [comment]
@csandman I'm pretty sure it's not the react-select it's from chakra, because the images that i sent, the ordering issue is on table not select. I'm expected only select component styling that is overidden but the fact is other chakra component styling also overidden

**Comment by csandman** [comment]
So that's the thing, this component doesn't do anything to modify the chakra provider.  I'm not even sure if that's possible to do from inside a component.  That's why I think it must have something to do with the way react-select itself interacts with emotion, because nothing this wrapper does should affect the rest of your Chakra styles.

The only way this component interacts with your chakra provider is to grab some existing component styles out of it.

**Comment by csandman** [comment]
If you could confirm/deny my theory by trying with the core `react-select` instead, that would help me to help you.

```sh
npm i react-select
```

```jsx
import Select from "react-select"
```

**Comment by fransiscushermanto** [comment]
> If you could confirm/deny my theory by trying with the core `react-select` instead, that would help me to help you.
> 
> ```shell
> npm i react-select
> ```
> 
> ```js
> import Select from "react-select"
> ```

Okay i'll try it. I'll inform you after i try it

**Comment by fransiscushermanto** [comment]
Hi @csandman, I'm sorry you are right the issue comes from react-select. Do you have any solution for it?

**Comment by fransiscushermanto** [comment]
Hi @csandman I've found the solution. I've found out the solution in react-select issues, source: https://github.com/JedWatson/react-select/issues/4953 Thanks for your help!

**Comment by csandman** [comment]
Glad you figured it out! And thanks for posting your solution here, could help someone else.
